version: "3"
services:
  app:
    cpus: 4
    mem_limit: 8g
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    #image: datajoint/element_deeplabcut:latest
    extra_hosts:
      - fakeservices.datajoint.io:127.0.0.1
    environment:
      - DJ_PUBLIC_S3_LOCATION=djhub.vathes.datapub.elements:/workflow-dlc-data/v2
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - ..:/workspaces/element-deeplabcut:cached
      - docker_data:/var/lib/docker # persist docker images
    privileged: true # only because of dind
volumes:
  docker_data:
