# MODE="LIVE|QA|PUSH" PACKAGE=element_deeplabcut UPSTREAM_REPO=https://github.com/datajoint/element-deeplabcut.git HOST_UID=$(id -u) docker compose -f docs/docker-compose.yaml up --build
# navigate to http://localhost/
#
# Check templates: https://github.com/dj-sciops/djsciops-cicd/tree/main/docker-template
version: "2.4"
services:
  docs:
    build:
      dockerfile: docs/.docker/Dockerfile
      context: ../
      args:
        - PACKAGE
    image: ${PACKAGE}-docs
    environment:
      - PACKAGE
      - UPSTREAM_REPO
      - MODE
      - PATCH_VERSION
      #- JUPYTER_PLATFORM_DIRS=1
    volumes:
      - ../docs:/main/docs
      - ../${PACKAGE}:/main/${PACKAGE}
      - ../notebooks:/main/notebooks
    user: ${HOST_UID}:anaconda
    ports:
      - 80:80
    command:
      - sh
      - -c
      - |
        git config --global --add safe.directory /main
        set -e
        export ELEMENT_UNDERSCORE=$$(echo $${PACKAGE} | sed 's/element_//g')
        export ELEMENT_HYPHEN=$$(echo $${ELEMENT_UNDERSCORE} | sed 's/_/-/g')
        export PATCH_VERSION=$$(cat /main/$${PACKAGE}/version.py | grep -oE '\d+\.\d+\.[a-z0-9]+')

        cp /main/notebooks/tutorial.ipynb /main/docs/src/tutorials/

        if echo "$${MODE}" | grep -i live &>/dev/null; then
            mkdocs serve --config-file ./docs/mkdocs.yaml -a 0.0.0.0:80 2>&1 | tee docs/temp_mkdocs.log
        elif echo "$${MODE}" | grep -iE "qa|push" &>/dev/null; then
            echo "INFO::Delete gh-pages branch"
            git branch -D gh-pages || true
            echo "INFO::Fetch upstream gh-pages"
            git fetch $${UPSTREAM_REPO} gh-pages:gh-pages && git switch gh-pages || git switch --orphan gh-pages && git commit --allow-empty -m "init commit"
            echo "INFO::mike"
            mike deploy --config-file ./docs/mkdocs.yaml -u $$(grep -oE '\d+\.\d+' /main/$${PACKAGE}/version.py) latest
            mike set-default --config-file ./docs/mkdocs.yaml latest
            if echo "$${MODE}" | grep -i qa &>/dev/null; then
                mike serve --config-file ./docs/mkdocs.yaml -a 0.0.0.0:80
            elif echo "$${MODE}" | grep -i push &>/dev/null; then
                echo "INFO::Push gh-pages to upstream"
                git push $${UPSTREAM_REPO} gh-pages
            fi
        else
            echo "Unexpected mode..."
            exit 1
        fi
