name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"
jobs:
  devcontainer-build:
    uses: datajoint/.github/.github/workflows/devcontainer-build.yaml@main
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py_ver: ["3.9", "3.10"]
        mysql_ver: ["8.0", "5.7"]
        include:
          - py_ver: "3.8"
            mysql_ver: "5.7"
          - py_ver: "3.7"
            mysql_ver: "5.7"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{matrix.py_ver}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.py_ver}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 "black[jupyter]"
      - name: Run style tests
        run: |
          python_version=${{matrix.py_ver}}
          black element_calcium_imaging --check --verbose --target-version py${python_version//.}
          black notebooks --check --verbose --target-version py${python_version//.}

